language: node_js
node_js:
  - "stable"
before_install:
    - rvm install 2.3.1
    - gem install sass
cache:
    directories:
    - node_modules
    - /home/travis/.rvm/
before_script:
  - npm install -g gulp-cli
script:
  - npm run build
  - gulp

