import React from 'react';
import AudioControl from '../AudioControl';
import imageOne from '../images/comment.png';
import imageTwo from '../images/AAJNEEI0.jpg';

const PageThree = props => {
	return (
		<div className="animated fadeIn">
			<section className="bodymatter">
				<div>
					<header><h1 className="title" id="P700101207800000000000000000AD3F" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD3F">Definition of Consciousness</h1></header>
					<section className="objectiveset" id="P7001012078000000000000000001B84" data-uri="M04_CICC7961_05_SE_C04.xhtml#P7001012078000000000000000001B84">
						<ol className="objectivelist dynamiclist" id="P700101207800000000000000000AD40" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD40">
							<li className="objective" id="P7001012078000000000000000001B86" data-uri="M04_CICC7961_05_SE_C04.xhtml#P7001012078000000000000000001B86"><p id="P700101207800000000000000000AD41" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD41"><span className="number">4.1</span> Define what it means to be conscious.</p></li>
						</ol>
					</section>
					<AudioControl src="https://mediaplayer.pearsoncmg.com/assets/_audio.true/audio-mypsychlab-ciccarelli_0134450728-ciccarelli5_ch4mod1sec0" />
					<p id="P700101207800000000000000000AD42" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD42">Philosopher Daniel Dennett, in his 1991 book <cite>Consciousness Explained</cite>, asserts that (contrary to the opinion of William James in his 1894 text) there is no single stream of consciousness but rather multiple “channels,” each of which is handling its own tasks (<a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008313">Dennett, 1991</a>). All of these channels operate in parallel, a kind of chaos of consciousness. People must somehow organize all this conscious experience, and that organization is influenced by their particular social groups and culture.</p>
					<p id="P700101207800000000000000000AD43" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD43" data-chaucer-note-id={217026}>Do animals experience consciousness in the same way as people? That is a question too complex to answer fully here, but many researchers of animal behavior, language, and cognition have some reason to propose that there is a kind of consciousness in at least some animals, although its organization would naturally not be the same as human consciousness (<a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000007FF9">Block, 2005</a>; <a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008099">Browne, 2004</a>; <a className="biblioref" href="./#/ciccarelli/reference#P70010120780000000000000000087D3">Hurley &amp; Nudds, 2006</a>; <a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008951">Koch &amp; Mormann, 2010</a>). <a className="xref" href="ch07_pg0001.xhtml#P7001012078000000000000000003087"><span className="label">Chapter</span> <span className="number">Seven</span></a> in this text includes a discussion of animal language that touches on some of these issues. See <a className="xref" href="ch07_pg0018.xhtml#P70010120780000000000000000034EA"><span className="label">Learning Objective</span> <span className="number">7.14</span></a>.</p>
					<blockquote className="extract">
						<p><img className="inline thumbnail" alt={"comment"} height={485} width={481} src={imageTwo} />
							<img alt="Small text bubble" height={13} width={12} src={imageOne} /> So where does that leave us in the search for a working definition of consciousness?</p>
					</blockquote>
					<p className="continued" id="P700101207800000000000000000AD46" data-uri="M04_CICC7961_05_SE_C04.xhtml#P700101207800000000000000000AD46" data-chaucer-note-id={217027}>For our purposes, a more useful definition of consciousness might be the following: <a className="keyword" id="P7001012078000000000000000001B8D" data-uri="M04_CICC7961_05_SE_C04.xhtml#P7001012078000000000000000001B8D" href="./#/ciccarelli/glossary#P70010120780000000000000000075FA">Consciousness</a> is your awareness of everything that is going on around you and inside your own head at any given moment, which you use to organize your behavior (<a className="biblioref" href="./#/ciccarelli/reference#P700101207800000000000000000845D">Farthing, 1992</a>), including your thoughts, sensations, and feelings. In a cognitive neuroscience view, consciousness is generated by a set of action potentials in the communication among neurons just sufficient to produce a specific perception, memory, or experience in our awareness (<a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008283">Crick &amp; Koch, 1990</a>, <a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008285">2003</a>; <a className="biblioref" href="./#/ciccarelli/reference#P7001012078000000000000000008951">Koch &amp; Mormann, 2010</a>). In other words, your eyes see a dog, the neurons along the optic pathway to the occipital lobe’s visual cortex are activated, and the visual association cortex is activated to identify the external stimulus as a “dog.” Bam!—consciousness! See <a className="xref" href="ch02_pg0018.xhtml#P7001012078000000000000000000FF8"><span className="label">Learning Objective</span> <span className="number">2.12</span></a>.</p>
				</div>
			</section>
		</div>
	);
};

export default PageThree;
